from enum import Enum

class CaseType(str, Enum):
    FAILED_PAYMENT = "FAILED_PAYMENT"
    ABANDONED_CHECKOUT = "ABANDONED_CHECKOUT"
    FAILED_SUBSCRIPTION = "FAILED_SUBSCRIPTION"
    OVERDUE_INVOICE = "OVERDUE_INVOICE"

class CaseStatus(str, Enum):
    DETECTED = "DETECTED"
    PROCESSING = "PROCESSING"
    RECOVERED = "RECOVERED"
    ESCALATED = "ESCALATED"
    UNRECOVERABLE = "UNRECOVERABLE"

class GuardrailDecision(str, Enum):
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
