[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/revenue_recovery

[post_write_hooks]

[logging]
default_handler_level = INFO
